// Compiles the scenario into one Gemini system instruction per (character, chapter, clock),
// plus the public bundle the browser needs (assets/case-data.js).
//
//   node prompts/build-prompt.mjs            -> prompts/compiled/<chapter>/<id>.txt + assets/case-data.js
//   import { buildSystemInstruction, ... }   (server/server.mjs)
//
// Rules this file enforces:
// - A character's prompt only holds what that character knows at that moment. Witnessed events
//   are cut at the current game clock; lies, secrets and the cover story only exist after the murder.
// - The solution and any secret marked promptVisibility:"engine" never leave the server. The
//   confession reaches the model only as a [DIRECTOR] note once the engine opens the gate.
// - The public bundle holds no prompts and no confession text.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { logger } from '../server/log.mjs';
import { toMin, CONFESSION_NEEDS, buildSystemInstruction, publicBundle } from './prompt-core.mjs';
export * from './prompt-core.mjs';

const here = dirname(fileURLToPath(import.meta.url));
export const SCENARIO_FILE = join(here, '..', 'scenario', 'orient.json');
export const loadScenario = (file = SCENARIO_FILE) => JSON.parse(readFileSync(file, 'utf8'));


// CLI
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const log = logger('build-prompt');
  const s = loadScenario(process.argv[2]);
  log.info('scenario', { file: process.argv[2] || SCENARIO_FILE, id: s.id, characters: s.characters.length, evidence: s.evidence.length, chapters: s.chapters.length });
  const evIds = new Set(s.evidence.map((e) => e.id));
  for (const id of CONFESSION_NEEDS) if (!evIds.has(id)) log.warn('confession gate names unknown evidence', { id });
  for (const id of s.solution.accusationRequires.evidenceAnyThreeOf) if (!evIds.has(id)) log.warn('accusation names unknown evidence', { id });
  for (const c of s.characters) for (const x of c.secrets) if (x.unlocks && !evIds.has(x.unlocks)) log.warn('secret unlocks unknown evidence', { character: c.id, secret: x.id, unlocks: x.unlocks });
  let prompts = 0;
  for (const ch of s.chapters) {
    const dir = join(here, 'compiled', ch.id); mkdirSync(dir, { recursive: true });
    for (const c of s.characters.filter((x) => x.chapters.includes(ch.id))) {
      const t = buildSystemInstruction(s, c.id, ch.id, toMin(ch.end));
      writeFileSync(join(dir, `${c.id}.txt`), t + '\n');
      prompts++; log.debug('prompt', { chapter: ch.id, character: c.id, chars: t.length });
    }
  }
  writeFileSync(join(here, '..', 'assets', 'case-data.js'), `// Generated by prompts/build-prompt.mjs from scenario/orient.json - do not edit.\nwindow.CASE = ${JSON.stringify(publicBundle(s), null, 1)};\n`);
  log.info('wrote', { prompts, dir: 'prompts/compiled/', bundle: 'assets/case-data.js' });
}
